### PR TITLE
Allow leading +1 in phoneUS validation

### PR DESCRIPTION
**Pull request by nitriques**
image

### CODE REVIEW

**Comment by PascalPiche** [comment]
Will match -> -5148395856

**Comment by PascalPiche** [comment]
image

**Comment by nitriques** [comment]
@fhamon this is normal. `\` are escaped to make them single `\` in the js string. Then is act as the escaping character in the regexp. In other words, the escaping character needs to be escaped. (Remove the extra \ in regexp101 and it will work)

**Comment by fhamon** [comment]
@nitriques Alright.

**Comment by nitriques** [comment]
ping @PascalPiche

**Comment by PascalPiche** [comment]
Will approve but still hope we will get a better regex one day.

**Pull request merged**
