### PR TITLE
Experimental module to keep the scroll position across page navigation

### PR DESCRIPTION
**Pull request by PascalPiche**

### CODE REVIEW

**Comment by nitriques** [comment]
Is this well tested now ?

**Comment by PascalPiche** [comment]
Still need test in the next project

**Comment by nitriques** [comment]
Is it safe to merge? I.E the scroll keeping can be turned off if the module is not in the js.json file...

**Comment by nitriques** [comment]
Still waiting for some other commits...

**Comment by PascalPiche** [comment]
Ready to merge

**Pull request merged**
