### PR TITLE
Add fix to jit bg image size

### PR DESCRIPTION
**Pull request by dominic-blain**
Creating a PR to have this code more easily accessible than in a upsource review. This is the corrected version based on your reviews.

It fixes the background image sizes only (most of the time the problem is with bg images).
I know it would be better to have a complete solution but still better than no solution.

### CODE REVIEW

**Comment by dominic-blain** [comment]
Needs [PR 298](https://github.com/DeuxHuitHuit/symphonycms-template/pull/298)

**Comment by nitriques** [comment]
ping @DeuxHuitHuit/symphony-2-template

**Comment by dominic-blain** [comment]
Can we put a DO NOT MERGE label here? After talking with @PascalPiche, i'll try something else.

**Comment by PascalPiche** [comment]
Algo ported in the core of the jquery-jit-image extension. This Pull Request can be closed.
See here: https://github.com/DeuxHuitHuit/jQuery-jit-image/pull/5

**Pull request closed without merging**
